export const actionTypes = {

    //auth
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT: 'LOGOUT',

    //user
    GET_ALL_USERS_SUCCESS: 'GET_ALL_USERS_SUCCESS',
    GET_ALL_USERS_FAIL: 'GET_ALL_USERS_FAIL',
    GET_ALL_FRIEND_SUCCESS: 'GET_ALL_FRIEND_SUCCESS',
    GET_ALL_FRIEND_FAIL: 'GET_ALL_FRIEND_FAIL',

    //app
    REFRESH: 'REFRESH',
    START_SOCKET: 'START_SOCKET'
}